-- Intentionally a no-op. Superseded by 20260915120000_push_tokens_token_unique.sql.
--
-- This version (20260517000000) was written as the push_tokens change
-- UNIQUE (user_id, expo_push_token) -> UNIQUE (expo_push_token). It never ran
-- in production:
--
--   * live_message_reports first used version 20260517000000 and was later
--     renamed to 20260517000003 (commit 3f0dcf6). The ledger had already
--     recorded 20260517000000 under the name `live_message_reports`, and
--     records it again at 20260517000003.
--   * So `supabase_migrations.schema_migrations` says 20260517000000 is
--     applied, `db push` skips this file, and the 2026-08-31 ledger repair,
--     which matched on version, did not notice.
--   * Verified 2026-09-15 against pg_constraint: push_tokens still has only
--     push_tokens_user_id_expo_push_token_key (user_id, expo_push_token).
--
-- WHY THE FILE IS KEPT BUT ITS SQL IS NOT
-- Deleting the file would leave a ledger row with no file, which `db push`
-- refuses until the ledger is repaired, so the history stays. Leaving the SQL
-- here would keep telling anyone reading the repo, and any check that parses
-- migrations, that production has a constraint it does not have. That is the
-- exact false belief behind four months of failed token saves. A fresh
-- database built from this directory also has to end up with the constraint
-- exactly once, so the SQL now lives in the new, idempotent migration.
--
-- The original SQL is in git history (commit 58ab62d). It opened with a
-- de-duplicating DELETE; the replacement checks for duplicates instead of
-- deleting them.
--
-- No ledger repair is needed for this version: the row that exists for it
-- stays, and it now describes a no-op. The single statement below keeps the
-- file a valid, non-empty migration for tools that replay the directory.

SELECT 1;
